#!/usr/bin/env bash
##
## Given a text file `file.txt` that contains a list of phone numbers (one per
## line), write a one-liner bash script to print all valid phone numbers.
##
## You may assume that a valid phone number must appear in one of the following
## two formats: `(xxx) xxx-xxxx` or `xxx-xxx-xxxx`. (`x` means a digit)
##
## You may also assume each line in the text file must not contain leading or
## trailing white spaces.
##
## == Example
##
## Assume that `file.txt` has the following content:
##
## ```Txt
## 987-123-4567
## 123 456 7890
## (123) 456-7890
## ```
##
## Your script should output the following valid phone numbers:
##
## ```Txt
## 987-123-4567
## (123) 456-7890
## ```
##

while IFS= read -r phone_number; do
    case "$phone_number" in 
        [0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9])
            echo "$phone_number"
            ;;
        \([0-9][0-9][0-9]\)\ [0-9][0-9][0-9]-[0-9][0-9][0-9][0-9])
            echo "$phone_number"
            ;;
    esac
done < "${1:-file.txt}"
